name: Download

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 15
  # download-latest:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #     - name: Test
  #       run: cat artifact/sha | grep $GITHUB_SHA
  # download-branch:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         branch: master
  #     - name: Test
  #       run: cat artifact/sha | grep $GITHUB_SHA
  # download-pr:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   if: github.ref != 'refs/heads/master'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         pr: ${{github.event.pull_request.number}}
  #     - name: Test
  #       run: cat artifact/sha | grep $GITHUB_SHA
  download-commit:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TEST 1
        run: |
          echo ${{ github.sha }}
      # - name: TEST 2
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       console.log("Getting workflows")
      #       const workflows = await github.rest.actions.listRepoWorkflows({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #       })
      #       const upload = workflows.data.workflows.find(i => /upload/i.test(i.name))
      #       const runs = await github.rest.actions.listWorkflowRuns({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         workflow_id: upload.id,
      #       })
      #       console.log(runs.data)
      - name: Download
        uses: ./
        with:
          workflow: upload.yml
          name: artifact
          path: artifact
          commit: ${{ github.event.workflow_run.head_sha }}
      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
  # download-multiple:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #     - name: Test
  #       run: |
  #         cat artifact/sha | grep $GITHUB_SHA
  #         cat artifact1/sha1 | grep $GITHUB_SHA
  #         cat artifact2/sha2 | grep $GITHUB_SHA
  # download-empty-conclusion:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         workflow_conclusion:
  #     - name: Test
  #       run: cat artifact/sha | grep $GITHUB_SHA
  # download-skip-unpack:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         skip_unpack: true
  #     - name: Test
  #       run: |
  #         test -d artifact
  #         test -f artifact/artifact.zip
  #         ! test -d artifact/artifact
  #         ! test -f artifact.zip
  #         unzip -l artifact/artifact.zip
  # download-dry-run-exists:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       id: download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         dry_run: true
  #     - name: Test
  #       run: test ${{ steps.download.outputs.dry_run }} == true
  # download-dry-run-not-exists:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       id: download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: not-artifact
  #         path: artifact
  #         dry_run: true
  #     - name: Test
  #       run: test ${{ steps.download.outputs.dry_run }} == false
  # download-with-check-artifacts:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         check_artifacts: true
  #     - name: Test
  #       run: cat artifact/sha | grep $GITHUB_SHA
  # download-with-search-artifacts:
  #   runs-on: ubuntu-latest
  #   needs: wait
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download
  #       uses: ./
  #       with:
  #         workflow: upload.yml
  #         name: artifact
  #         path: artifact
  #         search_artifacts: true
  #     - name: Test
  #       run: cat artifact/sha | grep $GITHUB_SHA
